name: ytv
description: "YTV —— 只在官方页面内承载播放的电视节目客户端。"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  webview_flutter_platform_interface: 2.15.1
  webview_win_floating: 3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
